{{- if .Values.config.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    maxmemory {{ .Values.config.maxmemory }}
    maxmemory-policy {{ .Values.config.maxmemoryPolicy }}
    save "{{ .Values.config.save }}"
    appendonly "{{ .Values.config.appendonly }}"
{{- end }}
