apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: prom 
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }} 
  endpoints:
    - port: http 
      targetPort: {{ .Values.service.port }}
      path: /metrics 
      interval: 30s
      scheme: http