apiVersion: batch/v1
kind: CronJob
metadata:
  name: alpine-cronjob-long
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: alpine-sleep
        spec:
          restartPolicy: Never
          containers:
            - image: alpine
              name: alpine-sleep
              command:
                - 'sh'
                - '-c'
                - 'sleep 75'